### ISSUE TITLE
cannot enable service

### ISSUE THREAD

**Issue by SynapseScribe** [elesiuta/picosnitch#38]
on centos 9

sudo dnf install python-bcc
pipx install "picosnitch[full]"

[user@pc~]$ picosnitch systemd
Traceback (most recent call last):
  File "/home/user/.local/share/pipx/venvs/picosnitch/lib64/python3.9/site-packages/picosnitch.py", line 2629, in <module>
    sys.exit(start_picosnitch())
  File "/home/user/.local/share/pipx/venvs/picosnitch/lib64/python3.9/site-packages/picosnitch.py", line 2257, in start_picosnitch
    assert importlib.util.find_spec("bcc"), "Requires BCC https://github.com/iovisor/bcc/blob/master/INSTALL.md"
AssertionError: Requires BCC https://github.com/iovisor/bcc/blob/master/INSTALL.md

**Comment by elesiuta** [comment]
Fixed in v2.0.0 as the eBPF backend has been migrated from BCC to libbpf CO-RE
